// Drill-down section renderers. Each export takes the dashboard `ctx`
// (stats, previous, range, isAllTime, isGlobal, selected, plus
// calendarView for the When-you-play tab toggle) and returns the HTML
// for that section's full-page view.
//
// Pure rendering: no module-level dashboard state, no event wiring. The
// dashboard body binder (in stats-dashboard.js) attaches the few click
// handlers each section depends on (calendar view tabs, persona ladder
// rows, audience switch).

import { TOOLS_BY_ID } from '../tools-table.js';
import { gradientSparkline, smoothPath } from './charts.js';
import { focusedLayout } from './focused-layout.js';
import {
  deltaInline,
  escapeHTML,
  formatBucketLabel,
  formatDuration,
  formatN,
  percentile,
} from './format.js';
import {
  DOW_LABELS,
  insightFacts,
  sectionInsight,
  sumPerModelTotals,
} from './insights.js';
import { personaAccent, PERSONA_IDS, PERSONA_LABELS } from './persona-present.js';

// Local counter for SVG <radialGradient> ids generated by anatomySingle.
// Previously shared with charts.js; isolated here so the anatomy section
// can render even when no sparkline runs in the same paint.
let _gradUid = 0;

// === A. Hero KPIs ======================================================

export function renderKPIs(ctx) {
  const { stats, previous, isAllTime, isGlobal, selected } = ctx;
  const filtered = selected && selected.size > 0;
  const totals = filtered
    ? sumPerModelTotals(stats.per_model, selected)
    : (stats.totals || {});
  const prev = filtered
    ? sumPerModelTotals(previous?.per_model, selected)
    : (previous?.totals || {});
  // Aggregate timeseries doesn't carry per-persona breakdown for mood, so
  // when a filter is engaged we rebuild the hits sparkline from
  // per_model_timeseries (which is per-persona) and drop the mood sparklines
  // to empty rather than fake them. Honest > pretty.
  const buckets = stats.timeseries || [];
  const hasSpark = !filtered && buckets.length >= 2;
  const hSeries = filtered
    ? sumPerModelSeries(stats.per_model_timeseries, selected, 'hits')
    : buckets.map((b) => Number(b.hits || 0));
  const hasFilteredSpark = filtered && hSeries.length >= 2 && hSeries.some((v) => v > 0);
  const helpSeries = hasSpark ? buckets.map((b) => Number(b.help_mood || 0)) : null;
  const hurtSeries = hasSpark ? buckets.map((b) => Number(b.hurt_mood || 0)) : null;
  const playSeries = hasSpark ? buckets.map((b) => Number(b.play_ms || 0)) : null;

  // When filtered, the Hits sparkline uses per-persona series and gets the
  // first-selected persona's accent so the tile reads as belonging to the
  // filter; mood sparklines drop because per_model_timeseries doesn't carry
  // mood. Help Ratio replaces Play Time, since play_ms isn't tracked
  // per-persona.
  const filterAccent = filtered ? personaAccent([...selected][0]) : null;
  const hitsAccent = filtered ? filterAccent : 'var(--ink)';

  const tiles = [];
  if (isGlobal) {
    tiles.push(kpi({
      label: 'Total Hits',
      value: formatN(totals.hits),
      delta: '',
      spark: hasSpark ? hSeries : (hasFilteredSpark ? hSeries : null),
      accent: hitsAccent,
    }));
    tiles.push(kpi({
      label: 'Help',
      value: formatN(totals.help_mood),
      delta: '',
      spark: hasSpark ? helpSeries : null, accent: 'var(--success)',
    }));
    tiles.push(kpi({
      label: 'Hurt',
      value: formatN(totals.hurt_mood),
      delta: '',
      spark: hasSpark ? hurtSeries : null, accent: 'var(--danger)',
    }));
    const totalActivity = (totals.help_mood || 0) + (totals.hurt_mood || 0);
    const helpRatio = totalActivity ? (totals.help_mood || 0) / totalActivity : 0.5;
    tiles.push(kpi({
      label: 'Help Ratio',
      value: `${Math.round(helpRatio * 100)}%`,
      delta: '',
      spark: null, accent: helpRatio >= 0.5 ? 'var(--success)' : 'var(--danger)',
    }));
  } else if (filtered) {
    const totalActivity = (totals.help_mood || 0) + (totals.hurt_mood || 0);
    const helpRatio = totalActivity ? (totals.help_mood || 0) / totalActivity : 0.5;
    tiles.push(kpi({
      label: 'Total Hits',
      value: formatN(totals.hits),
      delta: previous && !isAllTime ? deltaInline(totals.hits, prev.hits) : '',
      spark: hasFilteredSpark ? hSeries : null, accent: hitsAccent,
    }));
    tiles.push(kpi({
      label: 'Help Mood',
      value: formatN(totals.help_mood),
      delta: previous && !isAllTime ? deltaInline(totals.help_mood, prev.help_mood) : '',
      spark: null, accent: 'var(--success)',
    }));
    tiles.push(kpi({
      label: 'Hurt Mood',
      value: formatN(totals.hurt_mood),
      delta: previous && !isAllTime ? deltaInline(totals.hurt_mood, prev.hurt_mood) : '',
      spark: null, accent: 'var(--danger)',
    }));
    tiles.push(kpi({
      label: 'Help Ratio',
      value: totalActivity ? `${Math.round(helpRatio * 100)}%` : '—',
      delta: '',
      spark: null, accent: helpRatio >= 0.5 ? 'var(--success)' : 'var(--danger)',
    }));
  } else {
    tiles.push(kpi({
      label: 'Total Hits',
      value: formatN(totals.hits),
      delta: previous && !isAllTime ? deltaInline(totals.hits, prev.hits) : '',
      spark: hasSpark ? hSeries : null, accent: 'var(--ink)',
    }));
    tiles.push(kpi({
      label: 'Help Mood',
      value: formatN(totals.help_mood),
      delta: previous && !isAllTime ? deltaInline(totals.help_mood, prev.help_mood) : '',
      spark: hasSpark ? helpSeries : null, accent: 'var(--success)',
    }));
    tiles.push(kpi({
      label: 'Hurt Mood',
      value: formatN(totals.hurt_mood),
      delta: previous && !isAllTime ? deltaInline(totals.hurt_mood, prev.hurt_mood) : '',
      spark: hasSpark ? hurtSeries : null, accent: 'var(--danger)',
    }));
    tiles.push(kpi({
      label: 'Play Time',
      value: formatDuration(totals.play_ms),
      delta: previous && !isAllTime ? deltaInline(totals.play_ms, prev.play_ms) : '',
      spark: hasSpark ? playSeries : null, accent: 'var(--info)',
    }));
  }
  const eyebrow = isGlobal ? 'Across every player' : (filtered ? 'Filtered to your selected personas' : 'Your headline numbers');
  return `
    <section class="sd-section" data-section="kpi" data-filtered="${filtered ? '1' : '0'}">
      <header class="sd-section-head">
        <div>
          <div class="sd-section-eyebrow">${escapeHTML(eyebrow)}</div>
          <h2 class="sd-section-title">Overview</h2>
        </div>
      </header>
      <div class="sd-section-body">
        <div class="sd-kpi-row">${tiles.join('')}</div>
        ${renderBenchmarkStrip(ctx, totals)}
        ${filterScopeNote(ctx, { hint: filtered ? 'Headline numbers follow your buddy filter. Mood sparklines stay hidden because mood is only stored for the full set.' : null })}
      </div>
    </section>
  `;
}

// Single-line "vs global" comparison rendered below the overview KPIs when the
// benchmark toggle is on. Compares help-ratio directly (cleanly comparable
// across vastly different volumes) and notes the most-targeted persona
// globally, the two highest-signal facts derivable from leaderboard totals.
function renderBenchmarkStrip(ctx, totals) {
  const { benchmark, isGlobal, selected } = ctx;
  if (!benchmark || isGlobal) return '';
  // When a persona filter is engaged, restrict the global side to the same
  // subset so the comparison is apples-to-apples. Otherwise the user sees
  // their filtered ratio compared against an unfiltered global ratio, which
  // is misleading.
  const filtered = selected && selected.size > 0;
  const gTotals = filtered
    ? sumPerModelTotals(benchmark.per_model, selected)
    : (benchmark.totals || {});
  const personalActivity = (totals.help_mood || 0) + (totals.hurt_mood || 0);
  const globalActivity = (gTotals.help_mood || 0) + (gTotals.hurt_mood || 0);
  if (globalActivity === 0) return '';
  const personalRatio = personalActivity ? (totals.help_mood || 0) / personalActivity : null;
  const globalRatio = (gTotals.help_mood || 0) / globalActivity;
  const gPerModel = benchmark.per_model || {};
  let topId = null;
  let topHits = 0;
  for (const [id, m] of Object.entries(gPerModel)) {
    const hits = Number(m?.hits || 0);
    if (hits > topHits) { topHits = hits; topId = id; }
  }
  const topLabel = topId ? PERSONA_LABELS[topId] || topId : null;
  const topShare = topId && globalActivity
    ? Math.round((Number(gPerModel[topId]?.hits || 0) / Math.max(1, Number(gTotals.hits || 0))) * 100)
    : null;

  const ratioPct = (r) => `${Math.round(r * 100)}%`;
  const ratioCmp = personalRatio == null ? '' : (() => {
    const delta = Math.round((personalRatio - globalRatio) * 100);
    const sign = delta > 0 ? '+' : '';
    const dir = delta >= 0 ? 'kinder' : 'rougher';
    return `<span class="sd-bench-delta ${delta >= 0 ? 'pos' : 'neg'}">${sign}${delta}pp ${dir} than global</span>`;
  })();
  const topFragment = topLabel && topShare
    ? `<span class="sd-bench-fact">Globally most-targeted: <strong>${escapeHTML(topLabel)}</strong> (${topShare}% of hits)</span>`
    : '';
  return `
    <div class="sd-bench-strip" data-bench-strip>
      <span class="sd-bench-pill">
        <span class="sd-bench-pill-eyebrow">Global help ratio</span>
        <span class="sd-bench-pill-value">${ratioPct(globalRatio)}</span>
      </span>
      ${ratioCmp}
      ${topFragment}
    </div>
  `;
}

function kpi({ label, value, delta, spark, accent }) {
  const sparkHtml = Array.isArray(spark) && spark.length >= 2
    ? gradientSparkline(spark, { accent, height: 56, lineWidth: 1.5 })
    : `<svg class="sd-spark sd-spark-empty" viewBox="0 0 240 56" preserveAspectRatio="none" aria-hidden="true">
         <line x1="0" y1="40" x2="240" y2="40" stroke="${accent}" stroke-opacity=".18" stroke-dasharray="2 4" stroke-width="1" vector-effect="non-scaling-stroke"/>
       </svg>`;
  return `
    <div class="sd-kpi">
      <div class="sd-kpi-eyebrow">${escapeHTML(label)}</div>
      <div class="sd-kpi-row-2">
        <div class="sd-kpi-num">${value}</div>
        ${delta ? `<div class="sd-kpi-delta">${delta}</div>` : ''}
      </div>
      <div class="sd-kpi-spark" style="--accent:${accent};">${sparkHtml}</div>
    </div>
  `;
}

// === B. Pulse ==========================================================

export function renderPulse(ctx) {
  const { stats, selected } = ctx;
  const buckets = stats.timeseries || [];
  if (buckets.length < 2) {
    const insight = sectionInsight('activity', ctx, { empty: true });
    return focusedLayout({
      id: 'pulse', ctx,
      title: 'Day by day',
      ...insight,
      viz: empty('Not enough days yet.'),
    });
  }

  const perModelBuckets = stats.per_model_timeseries || [];
  const overlay = buildBenchmarkOverlay(buckets, ctx);
  let body;
  if (selected.size === 0) {
    body = pulseHelpHurt(buckets, overlay);
  } else if (selected.size === 1) {
    body = pulsePerPersona(perModelBuckets, [...selected]);
  } else if (selected.size <= 3) {
    body = pulsePerPersona(perModelBuckets, [...selected]);
  } else {
    body = pulseSmallMultiples(perModelBuckets, [...selected]);
  }

  const insight = sectionInsight('activity', ctx);
  let vizNote = selected.size === 0
    ? '**Green** rises with helpful mood, **red** falls with hurt mood, and the dark line shows __net direction|Net direction = helpful mood minus hurt mood, plotted across the visible range.__.'
    : 'Each line is one selected buddy. Hover the chart for the date and interaction count.';
  if (overlay && selected.size === 0) {
    vizNote += ' The faint dashed lines show the **global rhythm** for the same window, scaled to your axis, compare the shape, not the height.';
  }
  return focusedLayout({
    id: 'pulse', ctx, title: 'Day by day',
    ...insight,
    vizNote,
    viz: body,
  });
}

// Pulls per-day help/hurt counts from ctx.benchmarkSeries, sums them per
// day (optionally restricted to selected personas), then aligns to the
// personal buckets by UTC date. Returns null when the overlay isn't
// applicable (toggle off, series empty, or every personal bucket has zero
// global activity). Hour-grained personal buckets collapse to the same
// day key, that's intentional: a step-flat overlay reads as "this is the
// rhythm of the day overall," not minute-by-minute.
function buildBenchmarkOverlay(personalBuckets, ctx) {
  const { benchmarkSeries, selected } = ctx;
  if (!benchmarkSeries || !Array.isArray(benchmarkSeries.timeseries)) return null;
  if (benchmarkSeries.timeseries.length === 0) return null;
  const filter = selected && selected.size > 0 ? selected : null;
  const dayMap = new Map();
  for (const day of benchmarkSeries.timeseries) {
    if (!day || !day.date || !day.per_model) continue;
    let help = 0;
    let hurt = 0;
    for (const [modelId, m] of Object.entries(day.per_model)) {
      if (filter && !filter.has(modelId)) continue;
      help += Number(m?.help || 0);
      hurt += Number(m?.hurt || 0);
    }
    dayMap.set(day.date, { help, hurt });
  }
  if (dayMap.size === 0) return null;
  const utcDate = (ts) => {
    const d = new Date(Number(ts) || 0);
    if (Number.isNaN(d.getTime())) return null;
    return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
  };
  const helpSeries = [];
  const hurtSeries = [];
  let nonZero = false;
  for (const b of personalBuckets) {
    const key = utcDate(b.bucket_start);
    const row = key ? dayMap.get(key) : null;
    const help = row ? row.help : 0;
    const hurt = row ? row.hurt : 0;
    if (help > 0 || hurt > 0) nonZero = true;
    helpSeries.push(help);
    hurtSeries.push(hurt);
  }
  if (!nonZero) return null;
  return { helpSeries, hurtSeries };
}

function pulseHelpHurt(buckets, overlay) {
  const help = buckets.map((b) => Math.max(0, Number(b.help_mood || 0)));
  const hurt = buckets.map((b) => Math.max(0, Number(b.hurt_mood || 0)));
  const W = 696;
  const H = 220;            // data area (baseline + curve envelope)
  const tickBand = 22;      // reserved row below the data for x-axis labels
  const totalH = H + tickBand;
  const padX = 4;
  const baseline = H / 2;
  const halfH = H / 2 - 8;
  const maxAbs = Math.max(1, ...help, ...hurt);

  const xAt = (i) => padX + (i / (buckets.length - 1)) * (W - padX * 2);
  const yHelp = (v) => baseline - (v / maxAbs) * halfH;
  const yHurt = (v) => baseline + (v / maxAbs) * halfH;
  const helpPts = help.map((v, i) => ({ x: xAt(i), y: yHelp(v) }));
  const hurtPts = hurt.map((v, i) => ({ x: xAt(i), y: yHurt(v) }));
  const helpLine = smoothPath(helpPts);
  const hurtLine = smoothPath(hurtPts);
  const helpFill = `${helpLine} L ${helpPts[helpPts.length - 1].x.toFixed(2)} ${baseline} L ${helpPts[0].x.toFixed(2)} ${baseline} Z`;
  const hurtFill = `${hurtLine} L ${hurtPts[hurtPts.length - 1].x.toFixed(2)} ${baseline} L ${hurtPts[0].x.toFixed(2)} ${baseline} Z`;

  // Global overlay: scale each series to the personal axis so the shape
  // shows even though absolute units differ (mood-deltas vs raw counts).
  // Each side scales to its own personal peak so a quiet personal day isn't
  // visually swamped by a loud global day on the opposite polarity.
  let benchHelpPath = '';
  let benchHurtPath = '';
  if (overlay) {
    const benchHelpMax = Math.max(1, ...overlay.helpSeries);
    const benchHurtMax = Math.max(1, ...overlay.hurtSeries);
    const personalHelpMax = Math.max(1, ...help);
    const personalHurtMax = Math.max(1, ...hurt);
    const bhHelp = overlay.helpSeries.map((v) => (v / benchHelpMax) * personalHelpMax);
    const bhHurt = overlay.hurtSeries.map((v) => (v / benchHurtMax) * personalHurtMax);
    const bhHelpPts = bhHelp.map((v, i) => ({ x: xAt(i), y: yHelp(v) }));
    const bhHurtPts = bhHurt.map((v, i) => ({ x: xAt(i), y: yHurt(v) }));
    benchHelpPath = smoothPath(bhHelpPts);
    benchHurtPath = smoothPath(bhHurtPts);
  }

  const netPts = buckets.map((b, i) => {
    const net = (b.help_mood || 0) - (b.hurt_mood || 0);
    const y = net >= 0 ? yHelp(net) : yHurt(-net);
    return { x: xAt(i), y };
  });
  const netLine = smoothPath(netPts);

  const tickIdxs = [0, Math.floor(buckets.length / 2), buckets.length - 1];
  const tickY = H + tickBand - 6;  // baseline of text inside the tick band
  const ticks = tickIdxs.map((i) => {
    const ts = buckets[i].bucket_start || 0;
    const x = xAt(i);
    return `<text x="${x.toFixed(1)}" y="${tickY}" class="sd-tick" text-anchor="${i === 0 ? 'start' : i === buckets.length - 1 ? 'end' : 'middle'}">${formatBucketLabel(ts)}</text>`;
  }).join('');

  const stripWidth = (W - padX * 2) / buckets.length;
  const strips = buckets.map((b, i) => {
    const help = b.help_mood || 0;
    const hurt = b.hurt_mood || 0;
    const tip = `${formatBucketLabel(b.bucket_start)}\nhelp ${formatN(help)} · hurt ${formatN(hurt)}`;
    return `<rect class="sd-hit-strip" x="${(xAt(i) - stripWidth / 2).toFixed(1)}" y="0" width="${stripWidth.toFixed(1)}" height="${H}" data-tip="${escapeHTML(tip)}"/>`;
  }).join('');

  return `
    <svg class="sd-pulse" viewBox="0 0 ${W} ${totalH}" preserveAspectRatio="none">
      <defs>
        <linearGradient id="sd-help-grad" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0%" stop-color="var(--success)" stop-opacity="0.42"/>
          <stop offset="100%" stop-color="var(--success)" stop-opacity="0"/>
        </linearGradient>
        <linearGradient id="sd-hurt-grad" x1="0" x2="0" y1="1" y2="0">
          <stop offset="0%" stop-color="var(--danger)" stop-opacity="0.42"/>
          <stop offset="100%" stop-color="var(--danger)" stop-opacity="0"/>
        </linearGradient>
      </defs>
      <line class="sd-baseline" x1="0" y1="${baseline}" x2="${W}" y2="${baseline}"/>
      <path d="${helpFill}" fill="url(#sd-help-grad)"/>
      <path d="${hurtFill}" fill="url(#sd-hurt-grad)"/>
      ${benchHelpPath ? `<path d="${benchHelpPath}" class="sd-pulse-line sd-pulse-line-bench-help" vector-effect="non-scaling-stroke"/>` : ''}
      ${benchHurtPath ? `<path d="${benchHurtPath}" class="sd-pulse-line sd-pulse-line-bench-hurt" vector-effect="non-scaling-stroke"/>` : ''}
      <path d="${helpLine}" class="sd-pulse-line sd-pulse-line-help" vector-effect="non-scaling-stroke"/>
      <path d="${hurtLine}" class="sd-pulse-line sd-pulse-line-hurt" vector-effect="non-scaling-stroke"/>
      <path d="${netLine}" class="sd-pulse-line sd-pulse-line-net" vector-effect="non-scaling-stroke"/>
      ${ticks}
      ${strips}
    </svg>
  `;
}

function pulsePerPersona(perModelBuckets, ids) {
  const W = 696;
  const H = 220;
  const padX = 4;
  const padTop = 12;
  const padBottom = 22;
  const usableH = H - padTop - padBottom;

  const xVals = [...new Set(perModelBuckets.map((b) => b.bucket_start))].sort((a, b) => a - b);
  if (xVals.length < 2) {
    return empty('No buddy timeline in this window.');
  }
  const xIndex = new Map(xVals.map((x, i) => [x, i]));
  const xAt = (i) => padX + (i / (xVals.length - 1)) * (W - padX * 2);

  const seriesById = {};
  for (const id of ids) seriesById[id] = new Array(xVals.length).fill(0);
  for (const row of perModelBuckets) {
    if (!seriesById[row.model]) continue;
    seriesById[row.model][xIndex.get(row.bucket_start)] = (row.fires || 0) + (row.hits || 0);
  }
  const yMax = Math.max(1, ...ids.flatMap((id) => seriesById[id]));
  const yAt = (v) => padTop + (1 - v / yMax) * usableH;

  const lines = ids.map((id) => {
    const accent = personaAccent(id);
    const pts = seriesById[id].map((v, i) => ({ x: xAt(i), y: yAt(v) }));
    const path = smoothPath(pts);
    return `
      <path d="${path}" stroke="${accent}" fill="none" stroke-width="1.75"
            stroke-linecap="round" stroke-linejoin="round"
            vector-effect="non-scaling-stroke"/>
    `;
  }).join('');

  const tickIdxs = [0, Math.floor(xVals.length / 2), xVals.length - 1];
  const ticks = tickIdxs.map((i) => {
    const x = xAt(i);
    return `<text x="${x.toFixed(1)}" y="${(H - 6).toFixed(1)}" class="sd-tick" text-anchor="${i === 0 ? 'start' : i === xVals.length - 1 ? 'end' : 'middle'}">${formatBucketLabel(xVals[i])}</text>`;
  }).join('');

  const stripWidth = (W - padX * 2) / xVals.length;
  const strips = xVals.map((bs, i) => {
    const lines = ids.map((id) => `${PERSONA_LABELS[id]} ${formatN(seriesById[id][i])}`).join('\n');
    const tip = `${formatBucketLabel(bs)}\n${lines}`;
    return `<rect class="sd-hit-strip" x="${(xAt(i) - stripWidth / 2).toFixed(1)}" y="0" width="${stripWidth.toFixed(1)}" height="${H}" data-tip="${escapeHTML(tip)}"/>`;
  }).join('');

  const legend = ids.map((id) => `
    <span class="sd-legend-item" style="--accent:${personaAccent(id)};">
      <i></i>${escapeHTML(PERSONA_LABELS[id])}
    </span>
  `).join('');

  return `
    <svg class="sd-pulse" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">
      <line class="sd-baseline" x1="0" y1="${(H - padBottom).toFixed(1)}" x2="${W}" y2="${(H - padBottom).toFixed(1)}"/>
      ${lines}
      ${ticks}
      ${strips}
    </svg>
    <div class="sd-legend">${legend}</div>
  `;
}

function pulseSmallMultiples(perModelBuckets, ids) {
  // Independent y-axis per multiple: what matters here is shape, not
  // absolute comparability.
  const xVals = [...new Set(perModelBuckets.map((b) => b.bucket_start))].sort((a, b) => a - b);
  if (xVals.length < 2) return empty('No buddy timeline in this window.');
  const xIndex = new Map(xVals.map((x, i) => [x, i]));
  const seriesById = {};
  for (const id of ids) seriesById[id] = new Array(xVals.length).fill(0);
  for (const row of perModelBuckets) {
    if (!seriesById[row.model]) continue;
    seriesById[row.model][xIndex.get(row.bucket_start)] = (row.fires || 0) + (row.hits || 0);
  }
  const cells = ids.map((id) => {
    const accent = personaAccent(id);
    const series = seriesById[id];
    const total = series.reduce((a, b) => a + b, 0);
    return `
      <div class="sd-multi-cell">
        <div class="sd-multi-head">
          <span class="sd-multi-name">${escapeHTML(PERSONA_LABELS[id])}</span>
          <span class="sd-multi-num">${formatN(total)}</span>
        </div>
        <div class="sd-multi-spark" style="--accent:${accent};">
          ${gradientSparkline(series, { accent, height: 64, lineWidth: 1.4 })}
        </div>
      </div>
    `;
  }).join('');
  return `<div class="sd-multi-grid">${cells}</div>`;
}

// === C. Calendar =======================================================

export function renderCalendar(ctx) {
  const { stats, selected } = ctx;
  const view = ctx.calendarView || 'hourgrid';
  const tod = stats.time_of_day_heatmap || [];
  const cal = stats.daily_calendar || [];

  const tabs = `
    <div class="sd-cal-tabs">
      <button class="sd-cal-tab ${view === 'hourgrid' ? 'active' : ''}" data-calendar-view="hourgrid">Hour of week</button>
      <button class="sd-cal-tab ${view === 'streaks' ? 'active' : ''}" data-calendar-view="streaks">Daily streaks</button>
    </div>
  `;
  const filtered = selected && selected.size > 0;

  if ((view === 'hourgrid' && tod.length === 0) || (view === 'streaks' && cal.length === 0)) {
    const insight = sectionInsight('when', ctx, { empty: true, view });
    return focusedLayout({
      id: 'calendar', ctx,
      title: 'When you play',
      ...insight,
      viz: tabs + empty('No cadence yet.'),
    });
  }

  const body = view === 'hourgrid' ? hourGrid(tod) : dailyStreaks(cal);
  const insight = sectionInsight('when', ctx, { view });
  return focusedLayout({
    id: 'calendar', ctx, title: 'When you play',
    ...insight,
    vizNote: view === 'hourgrid'
      ? '__Darker squares|Cell intensity = bucket interactions divided by the busiest bucket in this chart, so the darkest square is the local peak.__ mean more interactions for that day and hour. Switch tabs to see daily streaks.'
      : 'Each square is a day. __Darker days|Cell intensity = day interactions divided by the busiest day in the visible calendar.__ had more activity. The streak count reads backward from today.',
    viz: tabs + body + filterScopeNote(ctx, { hint: filtered ? 'This cadence chart includes all buddies because hourly habits are not split by buddy yet.' : null }),
  });
}

function hourGrid(tod) {
  const grid = Array.from({ length: 7 }, () => new Array(24).fill(0));
  let max = 0;
  for (const cell of tod) {
    const v = (cell.fires || 0) + (cell.hits || 0);
    grid[cell.dow][cell.hour] = v;
    if (v > max) max = v;
  }
  if (max === 0) return empty('No activity in this window.');

  const rows = grid.map((row, dow) => {
    const cells = row.map((v, h) => {
      const intensity = v === 0 ? 0 : Math.min(1, v / max);
      const tip = `${DOW_LABELS[dow]} ${String(h).padStart(2, '0')}:00\n${formatN(v)} interactions`;
      return `<div class="sd-hgrid-cell" style="--intensity:${intensity.toFixed(3)};" data-tip="${escapeHTML(tip)}"></div>`;
    }).join('');
    return `
      <div class="sd-hgrid-row">
        <div class="sd-hgrid-rowlabel">${DOW_LABELS[dow]}</div>
        <div class="sd-hgrid-cells">${cells}</div>
      </div>
    `;
  }).join('');

  const hourLabels = [0, 6, 12, 18, 23].map((h) => `<span data-h="${h}">${String(h).padStart(2, '0')}</span>`).join('');

  return `
    <div class="sd-hgrid">
      ${rows}
      <div class="sd-hgrid-row sd-hgrid-axis">
        <div class="sd-hgrid-rowlabel"></div>
        <div class="sd-hgrid-axis-row">${hourLabels}</div>
      </div>
    </div>
  `;
}

function dailyStreaks(cal) {
  // Last 112 days (16 weeks). Sundays start the column. Sized for the
  // full-screen layout. Narrower windows wrap thanks to the parent grid.
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);
  const days = 112;
  const startMs = today.getTime() - (days - 1) * 86_400_000;
  const map = new Map(cal.map((d) => [d.date, d]));
  const cells = [];
  let max = 0;
  for (let i = 0; i < days; i++) {
    const ms = startMs + i * 86_400_000;
    const d = new Date(ms);
    const date = `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
    const row = map.get(date);
    const v = (row?.fires || 0) + (row?.hits || 0);
    if (v > max) max = v;
    cells.push({ date, ms, dow: d.getUTCDay(), v });
  }
  // Sequential layout: rows = DOW (0..6), columns advance every full week.
  const cols = [];
  let weekCol = [];
  // Pre-pad the first week so the first cell lands on its DOW row.
  const firstDow = cells[0].dow;
  for (let i = 0; i < firstDow; i++) weekCol.push(null);
  for (const c of cells) {
    weekCol.push(c);
    if (weekCol.length === 7) {
      cols.push(weekCol);
      weekCol = [];
    }
  }
  if (weekCol.length) {
    while (weekCol.length < 7) weekCol.push(null);
    cols.push(weekCol);
  }
  const colsHtml = cols.map((col) => {
    const cellsHtml = col.map((c) => {
      if (!c) return `<div class="sd-streak-cell sd-streak-empty"></div>`;
      const intensity = max ? Math.min(1, c.v / max) : 0;
      const tip = `${c.date}\n${formatN(c.v)} interactions`;
      return `<div class="sd-streak-cell" style="--intensity:${intensity.toFixed(3)};" data-tip="${escapeHTML(tip)}"></div>`;
    }).join('');
    return `<div class="sd-streak-col">${cellsHtml}</div>`;
  }).join('');
  const yLabels = `
    <div class="sd-streak-ylabels">
      <span></span><span>Mon</span><span></span><span>Wed</span><span></span><span>Fri</span><span></span>
    </div>
  `;
  // Streak number: count consecutive non-zero days backward from today.
  let streak = 0;
  for (let i = cells.length - 1; i >= 0; i--) {
    if (cells[i].v > 0) streak++;
    else break;
  }
  return `
    <div class="sd-streak">
      ${yLabels}
      <div class="sd-streak-cols">${colsHtml}</div>
    </div>
    <div class="sd-streak-meta">
      <span>${streak} day streak</span>
      <span>·</span>
      <span>${formatN(cells.reduce((a, c) => a + c.v, 0))} interactions across ${days} days</span>
    </div>
  `;
}

// === D. Anatomy =======================================================

export function renderAnatomy(ctx) {
  const { stats } = ctx;
  const heatmap = stats.hit_heatmap || [];
  if (heatmap.length === 0) {
    const insight = sectionInsight('where', ctx, { empty: true });
    return focusedLayout({
      id: 'anatomy', ctx,
      title: 'Where you hit',
      ...insight,
      viz: empty('No hits yet.'),
    });
  }
  const facts = insightFacts(ctx).anatomy;
  const ids = facts.ids;

  const viz = ids.length === 1
    ? anatomySingle(heatmap, ids[0])
    : `<div class="sd-anatomy-multi">${ids.map((id) => anatomySingle(heatmap, id, true)).join('')}</div>`;

  const insight = sectionInsight('where', ctx);
  return focusedLayout({
    id: 'anatomy', ctx, title: 'Where you hit',
    ...insight,
    vizNote: '__Brighter areas|Brightness = that body part\'s hits divided by the most-hit body part in this view.__ mark body parts with more recorded hits. Hover the figure or bars for exact counts.',
    viz,
  });
}

// Theme-aware neutral accent for the `_all` view. Returns a concrete hex
// so it can be used in SVG `stop-color` (which doesn't reliably resolve
// chained `var()` references through inline styles) and in JS-built
// color-mix strings.
function neutralAccentHex() {
  if (typeof document === 'undefined') return '#18181b';
  return document.body?.classList?.contains('theme-light') ? '#18181b' : '#ededf0';
}

function anatomySingle(heatmap, modelId, mini = false) {
  const filtered = modelId === '_all' ? heatmap : heatmap.filter((r) => r.character === modelId);
  const counts = { head: 0, torso: 0, arm: 0, leg: 0 };
  for (const r of filtered) counts[r.part] = (counts[r.part] || 0) + (r.count || 0);
  const total = counts.head + counts.torso + counts.arm + counts.leg;
  const max = Math.max(1, counts.head, counts.torso, counts.arm, counts.leg);
  const accent = modelId === '_all' ? neutralAccentHex() : personaAccent(modelId);
  const fIntensity = (count) => max ? Math.min(1, count / max) : 0;
  const headI = fIntensity(counts.head);
  const torsoI = fIntensity(counts.torso);
  const armI = fIntensity(counts.arm);
  const legI = fIntensity(counts.leg);

  const W = mini ? 180 : 280;
  const H = mini ? 250 : 380;
  const bloomId = `sd-bloom-${modelId}-${mini ? 'm' : 's'}-${++_gradUid}`;
  // Geometry mirrors physics/ragdoll.js exactly (head r=36, body r=44, arms
  // r=22 offset ±66 at y+82, legs r=26 offset ±26 at y+162) so the heatmap
  // reads as "this is the buddy" rather than a generic humanoid silhouette.
  // Origin (head center) lives at (100, 56) inside the 200×280 viewBox; the
  // figure spans roughly x=12..188 and y=20..238 with margin all around.
  const armBloomR = 22 + armI * 16;
  const legBloomR = 26 + legI * 18;
  const svg = `
    <svg class="sd-anatomy-svg" viewBox="0 0 200 280" preserveAspectRatio="xMidYMid meet" width="${W}" height="${H}">
      <defs>
        <radialGradient id="${bloomId}" cx="50%" cy="50%">
          <stop offset="0%" stop-color="${accent}" stop-opacity="0.85"/>
          <stop offset="100%" stop-color="${accent}" stop-opacity="0"/>
        </radialGradient>
      </defs>
      <circle cx="100" cy="50"  r="${(36 + headI * 24).toFixed(1)}"  fill="url(#${bloomId})" opacity="${headI.toFixed(3)}"/>
      <circle cx="100" cy="138" r="${(44 + torsoI * 30).toFixed(1)}" fill="url(#${bloomId})" opacity="${torsoI.toFixed(3)}"/>
      <circle cx="34"  cy="132" r="${armBloomR.toFixed(1)}"          fill="url(#${bloomId})" opacity="${armI.toFixed(3)}"/>
      <circle cx="166" cy="132" r="${armBloomR.toFixed(1)}"          fill="url(#${bloomId})" opacity="${armI.toFixed(3)}"/>
      <circle cx="74"  cy="212" r="${legBloomR.toFixed(1)}"          fill="url(#${bloomId})" opacity="${legI.toFixed(3)}"/>
      <circle cx="126" cy="212" r="${legBloomR.toFixed(1)}"          fill="url(#${bloomId})" opacity="${legI.toFixed(3)}"/>
      <g class="sd-anatomy-silhouette">
        <circle cx="100" cy="50"  r="36"/>
        <circle cx="100" cy="138" r="44"/>
        <circle cx="34"  cy="132" r="22"/>
        <circle cx="166" cy="132" r="22"/>
        <circle cx="74"  cy="212" r="26"/>
        <circle cx="126" cy="212" r="26"/>
      </g>
      <g class="sd-anatomy-hits">
        <circle cx="100" cy="50"  r="36" data-tip="${escapeHTML(`Head\n${formatN(counts.head)} hits`)}"/>
        <circle cx="100" cy="138" r="44" data-tip="${escapeHTML(`Torso\n${formatN(counts.torso)} hits`)}"/>
        <circle cx="34"  cy="132" r="22" data-tip="${escapeHTML(`Arms\n${formatN(counts.arm)} hits`)}"/>
        <circle cx="166" cy="132" r="22" data-tip="${escapeHTML(`Arms\n${formatN(counts.arm)} hits`)}"/>
        <circle cx="74"  cy="212" r="26" data-tip="${escapeHTML(`Legs\n${formatN(counts.leg)} hits`)}"/>
        <circle cx="126" cy="212" r="26" data-tip="${escapeHTML(`Legs\n${formatN(counts.leg)} hits`)}"/>
      </g>
    </svg>
  `;

  // Dominance + inline stacked bar replaces the old vertical list. The
  // ranked-by-count order encodes the hierarchy, and the bar's widths
  // encode share, so a glance tells you both "which part takes it" and
  // "how lopsided the distribution is." Inline labels render inside wide
  // segments and disappear (with a hover tooltip) on narrow ones.
  const ranked = [
    ['Head', counts.head], ['Torso', counts.torso],
    ['Arms', counts.arm], ['Legs', counts.leg],
  ].sort((a, b) => b[1] - a[1]);
  const [topLabel, topCount] = ranked[0];
  const topPct = total ? Math.round((topCount / total) * 100) : 0;
  const segments = ranked.map(([label, n], i) => {
    const pct = total ? (n / total) * 100 : 0;
    return { label, n, pct, rank: i };
  });
  // Bake colors at render time so SVG stop-color + CSS color-mix both
  // receive a literal value (chained CSS vars through inline styles are
  // unreliable across browsers in these contexts).
  const segTone = [1, 0.62, 0.38, 0.22];
  const segBg = (rank) => `color-mix(in srgb, ${accent} ${Math.round(segTone[rank] * 100)}%, var(--sd-surface))`;
  const stackHTML = segments.map((s) => {
    const wideEnough = s.pct >= 11;
    const textColor = s.rank <= 1 ? '#fff' : 'var(--sd-ink)';
    return `
      <span class="sd-anatomy-seg" data-rank="${s.rank}"
            style="flex-grow:${s.pct.toFixed(2)}; background:${segBg(s.rank)}; color:${textColor};"
            data-tip="${escapeHTML(`${s.label}\n${formatN(s.n)} hits · ${Math.round(s.pct)}%`)}">
        ${wideEnough
          ? `<span class="sd-anatomy-seg-inner"><span class="sd-anatomy-seg-label">${escapeHTML(s.label)}</span><span class="sd-anatomy-seg-pct">${Math.round(s.pct)}%</span></span>`
          : ''}
      </span>
    `;
  }).join('');
  const runners = segments.slice(1).map((s) => `
    <div class="sd-anatomy-runner">
      <span class="sd-anatomy-runner-dot" style="background:${segBg(s.rank)};"></span>
      <span class="sd-anatomy-runner-label">${escapeHTML(s.label)}</span>
      <span class="sd-anatomy-runner-num">${formatN(s.n)}</span>
    </div>
  `).join('');

  return `
    <div class="sd-anatomy ${mini ? 'sd-anatomy-mini' : ''}" style="--accent:${accent};">
      <div class="sd-anatomy-figure">${svg}</div>
      <div class="sd-anatomy-stats">
        ${mini ? `<div class="sd-anatomy-mini-name">${escapeHTML(modelId === '_all' ? 'all' : PERSONA_LABELS[modelId])}</div>` : ''}
        <div class="sd-anatomy-headline">
          <div class="sd-anatomy-eyebrow">Heaviest part</div>
          <div class="sd-anatomy-hero" style="color:${accent};">${escapeHTML(topLabel)}</div>
          <div class="sd-anatomy-cap">${formatN(topCount)} hits · ${topPct}% of ${formatN(total)} total</div>
        </div>
        <div class="sd-anatomy-stack" role="presentation">${stackHTML}</div>
        <div class="sd-anatomy-runners">${runners}</div>
      </div>
    </div>
  `;
}

// === E. Verb table ====================================================

export function renderVerbTable(ctx) {
  const { selected } = ctx;
  const verbs = insightFacts(ctx).tools.rows;

  if (verbs.length === 0) {
    const insight = sectionInsight('tools', ctx, { empty: true });
    return focusedLayout({
      id: 'verbs', ctx,
      title: 'Most used tools',
      ...insight,
      viz: empty('No tool data yet.'),
    });
  }

  const max = Math.max(1, ...verbs.map((v) => v.total));
  const rows = verbs.slice(0, 14).map((v) => {
    const pct = (v.total / max) * 100;
    const sparkHtml = v.series && v.series.length >= 2
      ? gradientSparkline(v.series, { accent: spineAccent(v.spine), height: 24, lineWidth: 1.2 })
      : '';
    const moodCol = v.moodSum >= 0
      ? `<span style="color:var(--success);">+${formatN(v.moodSum)}</span>`
      : `<span style="color:var(--danger);">${formatN(v.moodSum)}</span>`;
    return `
      <tr data-spine="${v.spine}" data-group="${v.group}">
        <td class="sd-verb-name">
          <span class="sd-verb-dot" style="background:${spineAccent(v.spine)};"></span>
          ${escapeHTML(v.label)}
        </td>
        <td class="sd-verb-spark">${sparkHtml}</td>
        <td class="sd-verb-num">${formatN(v.total)}</td>
        <td class="sd-verb-num">${moodCol}</td>
        <td class="sd-verb-bar"><i style="--pct:${pct.toFixed(1)}%; background:${spineAccent(v.spine)};"></i></td>
      </tr>
    `;
  }).join('');

  const filtered = selected && selected.size > 0;
  const table = `<table class="sd-verb-table">
      <thead>
        <tr>
          <th class="sd-verb-th-name">Tool</th>
          <th>Trend</th>
          <th class="sd-verb-th-num">Total</th>
          <th class="sd-verb-th-num">Mood impact</th>
          <th class="sd-verb-th-bar">Share</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>${filterScopeNote(ctx, { hint: filtered ? 'Tool totals include all buddies because individual tool use is not split by buddy yet.' : null })}`;

  const insight = sectionInsight('tools', ctx);
  return focusedLayout({
    id: 'verbs', ctx,
    title: 'Most used tools',
    ...insight,
    vizNote: 'Rows are ranked by total use. __Trend|Trend line = interaction count for that tool plotted across the selected range.__ shows recent activity, __Mood impact|Mood impact = sum of mood deltas across every recorded use of that tool. Positive helped, negative hurt.__ shows whether the tool helped or hurt, and __Share|Share = this tool\'s count divided by the most-used tool\'s count, drawn as a percentage bar.__ shows relative volume.',
    viz: table,
  });
}

function spineAccent(spine) {
  return spine === 'positive' ? 'var(--success)'
    : spine === 'negative' ? 'var(--danger)'
    : 'var(--ink)';
}

// === F. Persona ladder ===============================================

export function renderPersonaLadder(ctx) {
  const { selected, benchmark, isGlobal } = ctx;
  const rows = insightFacts(ctx).buddies.rows;

  if (rows.length === 0) {
    const insight = sectionInsight('buddies', ctx, { empty: true });
    return focusedLayout({
      id: 'personas', ctx,
      title: 'Buddies',
      ...insight,
      viz: empty('No buddy data yet.'),
    });
  }

  // Benchmark math: personalShare = how much of YOUR attention goes to this
  // persona; globalShare = how much of GLOBAL attention goes to them. Delta
  // (in percentage points) tells the user whether they favor that persona
  // more or less than the crowd does. Rendered as an explicit cell so the
  // signal can't hide behind the bright personal bar.
  const personalMax = Math.max(1, ...rows.map((r) => r.total));
  const gPerModel = (!isGlobal && benchmark?.per_model) || null;
  const personalTotal = rows.reduce((s, r) => s + r.total, 0) || 1;
  const globalTotal = gPerModel
    ? Object.values(gPerModel).reduce((s, m) => s + Number(m?.hits || 0), 0)
    : 0;
  const showDelta = gPerModel && globalTotal > 0;
  const html = rows.map((r) => {
    const accent = personaAccent(r.id);
    const helpBase = r.help + r.hurt || 1;
    const helpPct = (r.help / helpBase) * 100;
    const hurtPct = (r.hurt / helpBase) * 100;
    const widthPct = (r.total / personalMax) * 100;
    const dim = selected.size > 0 && !selected.has(r.id);
    const fav = r.fav ? (TOOLS_BY_ID[r.fav]?.label || r.fav) : '—';
    let deltaCell = '';
    if (showDelta) {
      const personalShare = r.total / personalTotal;
      const globalShare = Number(gPerModel[r.id]?.hits || 0) / globalTotal;
      const deltaPp = Math.round((personalShare - globalShare) * 100);
      const sign = deltaPp > 0 ? '+' : '';
      const cls = deltaPp > 0 ? 'pos' : deltaPp < 0 ? 'neg' : 'zero';
      deltaCell = `<div class="sd-ladder-delta ${cls}" title="vs global average">${sign}${deltaPp}pp</div>`;
    }
    return `
      <div class="sd-ladder-row ${showDelta ? 'has-delta' : ''}" data-ladder-row="${r.id}" data-dim="${dim ? '1' : '0'}">
        <div class="sd-ladder-name">
          <span class="sd-ladder-dot" style="background:${accent};"></span>
          ${escapeHTML(PERSONA_LABELS[r.id])}
        </div>
        <div class="sd-ladder-bar" style="width:${widthPct.toFixed(1)}%;">
          <i class="sd-ladder-bar-help" style="width:${helpPct.toFixed(1)}%;"></i>
          <i class="sd-ladder-bar-hurt" style="width:${hurtPct.toFixed(1)}%; left:${helpPct.toFixed(1)}%;"></i>
        </div>
        <div class="sd-ladder-num">${formatN(r.total)}</div>
        ${deltaCell}
        <div class="sd-ladder-fav">${escapeHTML(fav)}</div>
      </div>
    `;
  }).join('');

  const insight = sectionInsight('buddies', ctx);
  const baseNote = 'Each row is clickable. __Width|Bar width = that buddy\'s interactions divided by the most-played buddy\'s interactions in this view.__ shows total attention. The inner colors show how much of that play was helpful versus harmful.';
  const benchNote = showDelta
    ? ' The **vs global** column shows how your share of attention compares to the average player: __+Npp|You give this buddy N percentage points more of your attention than the average player does.__ means you favor that buddy more, **−Npp** means less.'
    : '';
  return focusedLayout({
    id: 'personas', ctx,
    title: 'Buddies',
    ...insight,
    vizNote: baseNote + benchNote,
    viz: `<div class="sd-ladder">${html}</div>`,
  });
}

// === G. Session distribution =========================================

export function renderSessions(ctx) {
  const { isGlobal } = ctx;
  if (isGlobal) {
    const insight = sectionInsight('sessions', ctx);
    return focusedLayout({
      id: 'sessions', ctx, myOnly: true,
      title: 'Sessions',
      ...insight,
      viz: empty('Personal - sessions only show for My Stats.'),
    });
  }
  const session = insightFacts(ctx).sessions;
  const rows = session.rows;
  if (rows.length === 0) {
    const insight = sectionInsight('sessions', ctx, { empty: true });
    return focusedLayout({
      id: 'sessions', ctx, myOnly: true,
      title: 'Sessions',
      ...insight,
      viz: empty('No sessions yet.'),
    });
  }

  const W = 696;
  const H = 200;
  const padX = 20;
  const padY = 22;

  const xMin = Math.min(...rows.map((r) => r.started_at));
  const xMax = Math.max(...rows.map((r) => r.started_at));
  const yMax = Math.max(1, ...rows.map((r) => r.fires + r.hits));
  const xAt = (t) => padX + ((t - xMin) / Math.max(1, xMax - xMin)) * (W - padX * 2);
  const yAt = (v) => H - padY - (v / yMax) * (H - padY * 2);

  const sorted = [...rows.map((r) => r.fires + r.hits)].sort((a, b) => a - b);
  const p10 = percentile(sorted, 0.1);
  const p25 = percentile(sorted, 0.25);
  const p50 = percentile(sorted, 0.5);
  const p75 = percentile(sorted, 0.75);
  const p90 = percentile(sorted, 0.9);
  const boxX = W - padX - 56;
  const box = `
    <line x1="${boxX}" y1="${yAt(p10)}" x2="${boxX}" y2="${yAt(p90)}" class="sd-box-whisker"/>
    <rect x="${boxX - 22}" y="${yAt(p75)}" width="44" height="${(yAt(p25) - yAt(p75)).toFixed(1)}" class="sd-box-iqr"/>
    <line x1="${boxX - 22}" y1="${yAt(p50)}" x2="${boxX + 22}" y2="${yAt(p50)}" class="sd-box-median"/>
  `;

  const stateColor = {
    ECSTATIC: 'var(--success)', HAPPY: '#7dd3fc', CONTENT: 'var(--ink)',
    WORRIED: '#fbbf24', HURT: '#fb923c', BROKEN: 'var(--danger)',
  };
  const dots = rows.map((r) => {
    const v = r.fires + r.hits;
    const x = xAt(r.started_at);
    const y = yAt(v);
    const fill = stateColor[r.end_state || 'CONTENT'] || 'var(--ink)';
    const tip = `${formatBucketLabel(r.started_at)}\n${formatN(v)} interactions\n${r.character || '—'} · ${r.end_state || '—'}`;
    return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="3.5" fill="${fill}" class="sd-dot" data-tip="${escapeHTML(tip)}"/>`;
  }).join('');

  const tickT = [xMin, (xMin + xMax) / 2, xMax];
  const ticks = tickT.map((t, i) => `<text x="${xAt(t).toFixed(1)}" y="${(H - 4).toFixed(1)}" class="sd-tick" text-anchor="${i === 0 ? 'start' : i === tickT.length - 1 ? 'end' : 'middle'}">${formatBucketLabel(t)}</text>`).join('');

  const viz = `<svg class="sd-sessions" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">
      <line class="sd-baseline" x1="0" y1="${H - padY}" x2="${W}" y2="${H - padY}"/>
      ${box}
      ${dots}
      ${ticks}
    </svg>
    <div class="sd-sessions-legend">
      ${Object.entries(stateColor).map(([s, c]) => `<span class="sd-legend-item" style="--accent:${c};"><i></i>${s.toLowerCase()}</span>`).join('')}
    </div>`;
  const insight = sectionInsight('sessions', ctx);
  return focusedLayout({
    id: 'sessions', ctx, myOnly: true,
    title: 'Sessions',
    ...insight,
    vizNote: 'Each dot is one session by start time. __Color|Dot color = mood state at session end (ECSTATIC, HAPPY, CONTENT, WORRIED, HURT, BROKEN).__ is the end mood state. The box marks the middle half of your sessions.',
    viz,
  });
}

// === H. Records =====================================================

export function renderRecords(ctx) {
  const { stats, isGlobal } = ctx;
  if (isGlobal) {
    const insight = sectionInsight('records', ctx);
    return focusedLayout({
      id: 'records', ctx, myOnly: true,
      title: 'Personal bests',
      ...insight,
      viz: empty('Personal - records only show for My Stats.'),
    });
  }
  const r = stats.records || {};
  const tiles = [
    record('Longest combo', formatN(r.longest_combo)),
    record('Biggest help', formatN(r.biggest_session_help)),
    record('Biggest hurt', formatN(r.biggest_session_hurt)),
    record('Longest session', formatDuration(r.longest_session_ms)),
  ].join('');

  const firstsRows = PERSONA_IDS.map((id) => {
    const firsts = stats.per_model?.[id]?.state_firsts || [];
    const states = ['ECSTATIC','HAPPY','CONTENT','WORRIED','HURT','BROKEN'];
    const dots = states.map((s) => {
      const seen = firsts.includes(s);
      return `<span class="sd-firsts-dot ${seen ? 'seen' : ''}" data-tip="${escapeHTML(`${PERSONA_LABELS[id]} · ${s.toLowerCase()}\n${seen ? 'seen' : 'not yet'}`)}"></span>`;
    }).join('');
    return `<div class="sd-firsts-row">
      <div class="sd-firsts-name"><span class="sd-firsts-accent" style="background:${personaAccent(id)};"></span>${escapeHTML(PERSONA_LABELS[id])}</div>
      <div class="sd-firsts-dots">${dots}</div>
    </div>`;
  }).join('');

  const insight = sectionInsight('records', ctx);

  return focusedLayout({
    id: 'records', ctx, myOnly: true,
    title: 'Personal bests',
    ...insight,
    vizNote: 'The top row is raw personal records. The dot grid below tracks __first-time mood states|First-time states = mood states each buddy has reached at least once. A filled dot means seen, an empty dot means not yet.__ per buddy.',
    viz: `<div class="sd-records-grid">${tiles}</div>
     <div class="sd-firsts-head">First-time mood states</div>
     <div class="sd-firsts">${firstsRows}</div>`,
  });
}

function record(label, value) {
  return `
    <div class="sd-record">
      <div class="sd-record-label">${escapeHTML(label)}</div>
      <div class="sd-record-value">${value}</div>
    </div>
  `;
}

// === I. Pareto: cost per mood ========================================

export function renderPareto(ctx) {
  const { isGlobal, selected } = ctx;
  if (isGlobal) {
    const insight = sectionInsight('value', ctx);
    return focusedLayout({
      id: 'pareto', ctx, myOnly: true,
      title: 'Best per coin',
      ...insight,
      viz: empty('Personal - switch to My Stats.'),
    });
  }
  const rows = insightFacts(ctx).value.rows;

  if (rows.length === 0) {
    const insight = sectionInsight('value', ctx, { empty: true });
    return focusedLayout({
      id: 'pareto', ctx, myOnly: true,
      title: 'Best per coin',
      ...insight,
      viz: empty('No paid tools used yet.'),
    });
  }

  const max = Math.max(...rows.map((r) => r.ratio));
  const html = rows.map((r) => {
    const pct = (r.ratio / max) * 100;
    const tip = `${r.label}\ncost ${formatN(r.cost)} coins · mood ${formatN(r.mood)}\n${r.ratio.toFixed(2)} mood per coin`;
    return `
      <div class="sd-pareto-row" data-tip="${escapeHTML(tip)}">
        <div class="sd-pareto-label">${escapeHTML(r.label)}</div>
        <div class="sd-pareto-bar">
          <i style="--pct:${pct.toFixed(1)}%; background:${spineAccent(r.spine)};"></i>
          <span class="sd-pareto-num">${r.ratio.toFixed(1)}</span>
        </div>
      </div>
    `;
  }).join('');

  const filtered = selected && selected.size > 0;
  const insight = sectionInsight('value', ctx);
  return focusedLayout({
    id: 'pareto', ctx, myOnly: true,
    title: 'Best per coin',
    ...insight,
    vizNote: 'Bars show __mood per coin|Mood per coin = absolute mood impact divided by coin cost. Higher means more mood movement returned per spent coin.__. Hover a row to see cost, mood impact, and the exact return.',
    viz: `<div class="sd-pareto">${html}</div>${filterScopeNote(ctx, { hint: filtered ? 'Value ranking uses all tool totals, not the selected buddy filter.' : null })}`,
  });
}

// --- helpers ----------------------------------------------------------
//
// Local rendering helpers shared across sections. `empty` is the inert
// placeholder shape; `filterScopeNote` is the inline annotation that
// keeps the user honest when a section can't honor the persona filter.

function empty(msg) {
  return `
    <div class="sd-empty">
      <svg viewBox="0 0 240 60" preserveAspectRatio="none" aria-hidden="true">
        <line x1="0" y1="30" x2="240" y2="30" stroke="currentColor" stroke-opacity=".22" stroke-dasharray="3 5" stroke-width="1" vector-effect="non-scaling-stroke"/>
      </svg>
      <p>${escapeHTML(msg)}</p>
    </div>
  `;
}

// Given per_model_timeseries rows ({model, bucket_start, fires, hits}),
// return a single time-aligned series summing `field` across selected
// personas. Buckets present anywhere in the data become the x-axis.
function sumPerModelSeries(perModelBuckets, selected, field) {
  if (!Array.isArray(perModelBuckets) || perModelBuckets.length === 0) return [];
  const xVals = [...new Set(perModelBuckets.map((b) => b.bucket_start))]
    .sort((a, b) => a - b);
  const idx = new Map(xVals.map((x, i) => [x, i]));
  const out = new Array(xVals.length).fill(0);
  for (const row of perModelBuckets) {
    if (!selected.has(row.model)) continue;
    const i = idx.get(row.bucket_start);
    out[i] = (out[i] || 0) + Number(row[field] || 0);
  }
  return out;
}

function filterScopeNote(ctx, { hint } = {}) {
  if (!hint) return '';
  return `<div class="sd-filter-note"><span class="sd-filter-note-bullet"></span>${escapeHTML(hint)}</div>`;
}
